language: objective-c
osx_image: xcode10.1
script:
- "./scripts/bluepill.sh build"
- "./scripts/bluepill.sh test"
before_deploy:
- |
  ZIP=$(echo build/Bluepill-*.zip)
  shasum -a 256 ${ZIP} > ${ZIP}.sha256
deploy:
  provider: releases
  api_key:
    secure: X93vGUqX+jKF4YeHy+ZyQuPQmpfanP2PaC/H//C/jHH0k6VKu1QMvALBKzPugl/cxIwTxJnIDfeTl8Zu+z7eFhHqVCkTaBtTATBgHWDuPaa82HYTT5VEzb4I4HnTeAp0N/VFPh7sXZRRU651wk5QxcyKHe7feNcPXAa/IEMOyfu1c8aoRzJjy8qghcVCs2ocjixBusku24bN4VPSzRlB8f7XOkjQ1Vi/nZ/z9b8MFhUDxGlZkXniLhgEE0CZ35zMFC3hR/A3crZMaZgEvwgK9cd1FGi9W1g2pEP3Vl/HZdQ4oe/Ma0boDB0hzdY0zRbY35Ch5/Ig0ZLkTSi//emZKUZIa6a8WQMUYk6K3IDjAiIntmi28I4Ggh3/QiRDaTaPmQt2PwUqicB6r3QS63tZ9GKLMedeT4oS4ICJFO55E8PoOkYn/CKTNy8YKG5pGYHMp0WzyiH9yu/p34iLDpw2+lznflO+al9J2EIOVcyD0A5CS0TWxWyNyeIz2JkhNh5gHyTDtpx6fFZ5R7PI/nl6WbyWzHzaoNr9WYQ+BPGcnlgUgeRjSFcP0S5LtMiW/B33mIuRaNUEMlqQZJc879SKeeWvBobCgeDPygw6s0hx2GNuQ3ChAAttSLxirSlusGWJPOIPZj5c4xz1bG+EtuKV0eyG7Lob88xRXwb9jnk1mxU=
  file: build/Bluepill-*.zip*
  file_glob: true
  draft: true
  on:
    repo: ob/bluepill
    branch: man-page-fix
